// GENERATED by scripts/generate-mobile-contract.ts. Do not edit.
// Millisecond durations are converted at the native API boundary.
enum MobileContract {
    static let contractVersion = 1
    static let eventNameLength = 80
    static let labelLength = 80
    static let userIdLength = 200
    static let appVersionLength = 80
    static let propertyCount = 40
    static let propertyKeyLength = 80
    static let propertyStringLength = 2000
    static let propertyArrayLength = 20
    static let propertyArrayStringLength = 200
    static let propertiesBytes = 8192
    static let onboardingSteps = 20
    static let onboardingQuestions = 20
    static let questionOptions = 20
    static let questionTitleLength = 160
    static let optionLabelLength = 80
    static let onboardingDefinitionBytes = 16384
    static let onboardingDefinitions = 100
    static let storeIdLength = 200
    static let paywallViews = 100
    static let paywallPurchases = 20
    static let providerIdLength = 255
    static let batchEvents = 100
    static let requestBytes = 1048576
    static let clientBatchBytes = 786432
    static let defaultBatchSize = 50
    static let defaultQueueSize = 1000
    static let maxQueueSize = 10000
    static let defaultFlushIntervalMs = 15000
    static let maxFlushIntervalMs = 86400000
    static let defaultRequestTimeoutMs = 10000
    static let maxRequestTimeoutMs = 300000
    static let maxBatchesPerFlush = 20
    static let retryMaximumMs = 60000
    static let retryAfterMaximumMs = 86400000
    static let feedbackMessageLength = 4000
    static let feedbackEmailLength = 254
    static let feedbackRequestBytes = 24576
    static let maximumSafeInteger = 9007199254740991
}
